import type { Metadata } from "next";
import { auth } from "@clerk/nextjs/server";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "The terms and conditions for using Arc AI's chat and coding agent platform.",
  alternates: { canonical: "/terms" },
};

export default async function TermsPage() {
  const { userId } = await auth();

  return (
    <div className="flex flex-1 flex-col">
      <SiteHeader signedIn={Boolean(userId)} />
      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-12">
        <article className="prose prose-sm dark:prose-invert max-w-none">
          <h1>Terms &amp; Conditions</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Last updated: this is placeholder content for a template project — review with
            counsel before relying on it for a real business.
          </p>

          <h2>1. Acceptance of terms</h2>
          <p>
            By creating an account or using Arc AI, you agree to these Terms &amp; Conditions.
            If you do not agree, do not use the service.
          </p>

          <h2>2. The service</h2>
          <p>
            Arc AI provides a chat interface to third-party large language models and a
            sandboxed coding agent. Responses are generated by AI and may be inaccurate or
            incomplete — you&rsquo;re responsible for verifying anything important before
            relying on it.
          </p>

          <h2>3. Credits, billing &amp; subscriptions</h2>
          <p>
            Usage is metered in credits. Credits are granted on signup, via a paid Pro
            subscription (billed monthly, auto-renewing until cancelled), or via one-time
            top-up purchases in the amount you choose at checkout. You can cancel a Pro
            subscription at any time from the billing page; access continues until the end
            of the current billing period.
          </p>

          <h2>4. Refunds</h2>
          <p>
            Credits already consumed are not refundable. Unused credit balances or accidental
            duplicate charges may be refunded at our discretion — contact support with your
            payment details and we&rsquo;ll take a look.
          </p>

          <h2>5. Acceptable use</h2>
          <p>
            Don&rsquo;t use Arc AI to generate illegal content, abuse the sandboxed coding
            agent to attack other systems, or attempt to circumvent usage limits or billing.
            We may suspend accounts that violate this.
          </p>

          <h2>6. Disclaimer &amp; liability</h2>
          <p>
            The service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
            maximum extent permitted by law, Arc AI is not liable for indirect, incidental, or
            consequential damages arising from your use of the service.
          </p>

          <h2>7. Contact</h2>
          <p>
            Questions about these terms? Email{" "}
            <a href="mailto:info@arcai.io">info@arcai.io</a>.
          </p>
        </article>
      </main>
      <SiteFooter />
    </div>
  );
}
